# Generated by Django 5.0.6 on 2024-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coupon_code',
            field=models.CharField(default=None, verbose_name=15),
            preserve_default=False,
        ),
    ]
