# Generated by Django 5.0.6 on 2024-07-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_course_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coupon_code',
            field=models.CharField(default='None', verbose_name=15),
        ),
    ]
