# Generated by Django 5.0.6 on 2024-07-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_course_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coupon_code',
        ),
    ]
