# Generated by Django 5.0.6 on 2024-07-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_course_creator_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.CharField(max_length=100),
        ),
    ]
