# Generated by Django 5.0.6 on 2024-07-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_course_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
    ]
