name: Build NyxAcademy Image

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GHCR_TOKEN}}
    - name: Build the Docker image
      run: |
        docker image build . --file Dockerfile --tag ghcr.io/thinknyx-technologies-llp/nyxacademy:$(date +%s)
        docker image push ghcr.io/thinknyx-technologies-llp/nyxacademy:$(date +%s)
